language: python
python:
  - "2.7"

install:
  - pip install -r tests/requirements.txt
  - pip install coveralls

script:
  - coverage run --source=labtronyx setup.py nosetests

after_success:
  coveralls